// The 15 cinematic stages, in scroll order. Image data (crop, blur placeholder,
// real dimensions) comes from public/frames/manifest.json, generated by
// scripts/prepare-frames.mjs from the raw Figma exports. This file only adds the
// human-facing label and the narrative grouping.

import manifest from '@/public/frames/manifest.json';

export interface FrameAsset {
  id: string; // "01".."15"
  stage: number;
  name: string;
  width: number;
  height: number;
  aspect: number;
  blur: string; // data: URI, tiny blurred placeholder
}

// Play order (by Figma stage number): the "Namaste / I am Vivek Patel" intro
// (11–15) runs first, then the "What can I do?" archery sequence (1–10).
const PLAY_ORDER = [11, 12, 13, 14, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

const byStage = new Map<number, FrameAsset>(
  (manifest.frames as FrameAsset[]).map((f) => [f.stage, f])
);

export const FRAMES: FrameAsset[] = PLAY_ORDER.map((n) => byStage.get(n)).filter(
  (f): f is FrameAsset => Boolean(f)
);
export const SRC_WIDTHS: number[] = manifest.widths;

/** `srcset` string for a frame id, e.g. "/frames/03-1600.webp 1600w, ..." */
export function frameSrcSet(id: string): string {
  return SRC_WIDTHS.map((w) => `/frames/${id}-${w}.webp ${w}w`).join(', ');
}

/** Default `src` (middle width) for browsers without srcset support. */
export function frameSrc(id: string): string {
  const mid = SRC_WIDTHS[Math.floor(SRC_WIDTHS.length / 2)];
  return `/frames/${id}-${mid}.webp`;
}
